version: '3.9'

services:
  mongodb:
    image: mongo:4.4.18
    container_name: mongodb_carres
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: QO%wpm101rO%NO9iYOPQ#4acbz36nj
    ports:
      - 27017:27017
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro
      - log:/var/log/mongodb
      - mongodb_data:/data/db

  redis:
    image: redis
    container_name: redis_cache
    restart: always
    ports:
      - 6379:6379

volumes:
  log:
  mongodb_data:
